landmark_choices = {
  'a': 'Playground',
  'b': 'Reception',
  'c': 'Student Center',
  'd': 'Central Street',
  'e': 'Library',
  'f': 'Wellness Center',
  'g': 'Projects Lab',
  'h': 'Cafe2Go',
  'i': 'Ehsaas Center',
  'j': 'Elements Courtyard',
  'k': 'Gym',
  'l': 'Mehfil',
  'm': 'Film Studio',
  'n': 'Baithak',
  'o': 'Arif Habib',
  'p': 'Chemistry And Ecology Lab',
  'q': 'Digital Systems And Instrumentation Lab/ Communications Lab ',
  'r': 'Soorty Hall',
  's': 'Student Lounge',
  't': 'Courts',
  'u': 'Dhaba/Garden',
  'v': 'Ampitheater',
  'w': 'Engineering Workshop',
  'x': 'Tapal Cafeteria',
  'y': 'Tariq Rafi Hall',
  'z': 'Auditorium'
}