hu_landmarks = {
  'Playground': set(['Reception Elevators']),
  'Reception': set(['Reception Elevators', "Back Passage", "Front Desk"]),
  'Student Center': set(['Reception Elevators', "OAP Exit"]),
  'Central Street': set(['Central Street 1', 'Central Street End']),
  'Library': set(['East Ramp', 'Library Elevator']),
  'Wellness Center': set(['Wellness Courtyard', "Back Passage"]),
  'Projects Lab': set(['Parking Lot Elevator', 'Tapal Courtyard']),
  'Cafe2Go': set(['East Ramp', "Library Courtyard"]),
  'Ehsaas Center': set(['Library Elevator']),
  'Elements Courtyard': set(['Central Ramp', "Back Passage", "Earth Courtyard Elevator", 'Water Courtyard Ramp']),
  'Gym': set(['Tapal Courtyard']),
  'Mehfil': set([]),
  'Film Studio': set(['1st Floor Bridge']),
  'Baithak': set(['1st Floor Elevator']),
  'Arif Habib': set(['Central Ramp']),
  'Chemistry And Ecology Lab': set(['Water Courtyard Ramp']),
  'Digital Systems And Instrumentation Lab/ Communications Lab ': set(['Water Courtyard Ramp']),
  'Soorty Hall': set(['Central Street End']),
  'Student Lounge': set(['Central Street End', "Student Lounge Entrance"]),
  'Courts': set(['Courts Bleachers', "Back Passage"]),
  'Dhaba/Garden': set(['Courts Ramp 2', 'Courts Bleachers', "Tapal Courtyard", "Raheem Bhai"]),
  'Ampitheater': set(["Ampi Stage", "Back Lockers"]),
  'Engineering Workshop': set(['Back Lockers']),
  'Tapal Cafeteria': set(["Tapal Courtyard"]),
  'Tariq Rafi Hall': set(['1st Floor Bridge']),
  'Auditorium': set(['Reception Elevators'])
}