hu_metro = {
  'Reception Elevators': set(['Front Desk', 'Parking Lot Elevator']),
  'Back Passage': set(['Front Desk', 'Wellness Courtyard', "Earth Courtyard Elevator",'Water Courtyard Ramp', 'Courts Bleachers']),
  'Front Desk': set(["Back Passage", 'Central Ramp', 'Reception Elevators']),
  'OAP Exit': set(['Wellness Courtyard']),
  'Library Courtyard': set(['East Ramp', 'Central Street 1', "Library Elevator"]),
  'Wellness Courtyard': set(['Central Street 1', 'OAP Exit', "Back Passage"]),
  'East Ramp': set(['Library Courtyard', 'Parking Lot Elevator', 'Tapal Courtyard']),
  'Tapal Courtyard': set(['Raheem Bhai', "Ampi Stage","East Ramp",'Parking Lot Elevator']),
  'Raheem Bhai': set(['Courts Ramp 2', 'Courts Bleachers', "Tapal Courtyard"]),
  'Back Lockers': set(["Ampi Stage", "Lower Ground Elevator"]),
  "Ampi Stage": set(['Back Lockers']),
  "Lower Ground Elevator": set(["Earth Courtyard Elevator"]),
  "Earth Courtyard Elevator": set(["Lower Ground Elevator",'1st Floor Elevator', 'Back Passage', 'Central Ramp', 'Water Courtyard Ramp']),
  "Lower Ground Elevator": set(["Earth Courtyard Elevator", '1st Floor Elevator']),
  '1st Floor Elevator': set(["Earth Courtyard Elevator", "Lower Ground Elevator", '1st Floor Bridge']),
  'Central Ramp': set(['Central Street 1', "Earth Courtyard Elevator",'Water Courtyard Ramp']),
  'Central Street 1': set(['Central Ramp', 'Wellness Courtyard', 'Library Courtyard', 'Central Street End']),
  'Central Street End': set([ 'Courts Ramp 1', "Student Lounge Entrance"]),
  "Student Lounge Entrance": set(['Central Street End',  'Courts Ramp 1']),
  'Courts Ramp 1': set(["Student Lounge Entrance", 'Central Street End']),
  'Courts Ramp 2': set(['Courts Bleachers', "Raheem Bhai"]),
  'Courts Bleachers': set(['Raheem Bhai','Back Passage','Courts Ramp 1']),
  '1st Floor Bridge': set(['1st Floor Elevator']),
  'Parking Lot Elevator': set(['Reception Elevators', 'Tapal Courtyard']),
  'Water Courtyard Ramp':set(['Central Ramp']),
  "Library Elevator" : set(['Library Courtyard'])
  
  }